# Generated by Django 5.1.3 on 2025-07-24 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guiziapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="Pregunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_pregunta", models.TextField()),
                (
                    "imagen_pregunta",
                    models.ImageField(blank=True, null=True, upload_to="quiz_images/"),
                ),
                ("tiempo_limite", models.IntegerField(default=20)),
            ],
        ),
        migrations.CreateModel(
            name="OpcionRespuesta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_opcion", models.CharField(max_length=255)),
                ("es_correcta", models.BooleanField(default=False)),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opciones",
                        to="guiziapp.pregunta",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="guiziapp.categoria",
                    ),
                ),
                (
                    "creador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quizzes_creados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pregunta",
            name="quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="preguntas",
                to="guiziapp.quiz",
            ),
        ),
        migrations.CreateModel(
            name="IntentoQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_anonimo",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("puntaje", models.IntegerField(default=0)),
                ("tiempo_transcurrido_segundos", models.IntegerField(default=0)),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_finalizacion", models.DateTimeField(blank=True, null=True)),
                ("completado", models.BooleanField(default=False)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="intentos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intentos",
                        to="guiziapp.quiz",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Intentos de Quizzes",
                "ordering": ["-puntaje", "tiempo_transcurrido_segundos"],
            },
        ),
        migrations.CreateModel(
            name="RespuestaUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("es_correcta", models.BooleanField(default=False)),
                ("tiempo_respuesta_segundos", models.IntegerField(default=0)),
                (
                    "intento_quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respuestas_individuales",
                        to="guiziapp.intentoquiz",
                    ),
                ),
                (
                    "opcion_seleccionada",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guiziapp.opcionrespuesta",
                    ),
                ),
                (
                    "pregunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="guiziapp.pregunta",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Respuestas de Usuarios",
            },
        ),
    ]
